# Generated by Django 2.2.19 on 2022-11-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221105_2356'),
        ('users', '0002_auto_20221104_0641'),
    ]

    operations = [
    ]
